# Generated by Django 3.2.16 on 2025-03-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_follow_unique_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
    ]
